#!/usr/bin/env bash
set -euo pipefail

API_BASE_URL="${API_BASE_URL:-http://localhost:8080}"
OUT_FILE="review_images_seed.sql"
MODE=""
MANIFEST=""
IMAGE_DIR=""
REVIEW_ID=""
BASE_URL="${OBJECT_STORAGE_BASE_URL:-}"

usage() {
  cat <<'USAGE'
Usage:
  scripts/upload_review_images.sh --manifest <csv> [--out <file>]
  scripts/upload_review_images.sh --dir <image_dir> --review-id <id> [--out <file>]

Manifest format (CSV, no header):
  review_id,filepath,sort_order

Env:
  API_BASE_URL (default: http://localhost:8080)
  OBJECT_STORAGE_BASE_URL (optional; used if API response doesn't return fileUrl)
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --manifest)
      MODE="manifest"
      MANIFEST="$2"
      shift 2
      ;;
    --dir)
      MODE="dir"
      IMAGE_DIR="$2"
      shift 2
      ;;
    --review-id)
      REVIEW_ID="$2"
      shift 2
      ;;
    --out)
      OUT_FILE="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "$MODE" ]]; then
  echo "Either --manifest or --dir is required." >&2
  usage
  exit 1
fi

if [[ "$MODE" == "manifest" && -z "$MANIFEST" ]]; then
  echo "--manifest requires a CSV path." >&2
  exit 1
fi

if [[ "$MODE" == "dir" ]]; then
  if [[ -z "$IMAGE_DIR" || -z "$REVIEW_ID" ]]; then
    echo "--dir mode requires --review-id." >&2
    exit 1
  fi
  if [[ ! -d "$IMAGE_DIR" ]]; then
    echo "Image directory not found: $IMAGE_DIR" >&2
    exit 1
  fi
fi

upload_file() {
  local file_path="$1"
  local response
  response=$(curl -sS -X POST \
    -F "file=@${file_path}" \
    "${API_BASE_URL}/api/v1/images/upload/reviews")

  local file_url
  local key
  file_url=$(echo "$response" | jq -r '.data.fileUrl // .fileUrl // empty')
  key=$(echo "$response" | jq -r '.data.key // .key // empty')

  if [[ -z "$file_url" && -n "$key" && -n "$BASE_URL" ]]; then
    file_url="${BASE_URL%/}/${key}"
  fi

  if [[ -z "$file_url" ]]; then
    echo "Upload failed or fileUrl missing for ${file_path}" >&2
    echo "Response: $response" >&2
    exit 1
  fi

  echo "$file_url"
}

echo "-- generated by scripts/upload_review_images.sh" > "$OUT_FILE"

if [[ "$MODE" == "manifest" ]]; then
  if [[ ! -f "$MANIFEST" ]]; then
    echo "Manifest file not found: $MANIFEST" >&2
    exit 1
  fi

  while IFS=, read -r review_id file_path sort_order; do
    [[ -z "${review_id// }" ]] && continue
    [[ "${review_id:0:1}" == "#" ]] && continue

    file_path="${file_path//\"/}"
    file_url=$(upload_file "$file_path")
    safe_url=$(printf "%s" "$file_url" | sed "s/'/''/g")

    echo "INSERT INTO review_images (review_id, image_url, sort_order) VALUES (${review_id}, '${safe_url}', ${sort_order});" >> "$OUT_FILE"
  done < "$MANIFEST"
else
  sort_order=0
  found_any=0
  while IFS= read -r file_path; do
    found_any=1
    file_url=$(upload_file "$file_path")
    safe_url=$(printf "%s" "$file_url" | sed "s/'/''/g")
    echo "INSERT INTO review_images (review_id, image_url, sort_order) VALUES (${REVIEW_ID}, '${safe_url}', ${sort_order});" >> "$OUT_FILE"
    sort_order=$((sort_order + 1))
  done < <(find "$IMAGE_DIR" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) | sort)

  if [[ "$found_any" -eq 0 ]]; then
    echo "No images found in: $IMAGE_DIR" >&2
    exit 1
  fi
fi

echo "SQL saved to ${OUT_FILE}"
